void inputAndCallCommand();
char *inputPath();
int newFile(char *address);
int checkPath(char *address);
int insert(char *address, char *string, int line, int pos);
int cat(char *address);
int removeString(char *address, int line, int pos, int length, char direction);
int copy(char *address, int line, int pos, int length, char direction);
int cut(char *address, int line, int pos, int length, char direction);
int paste(char *address, int line, int pos);